GET http://localhost:3000/
Accept: text/html

###
POST http://localhost:3000/add
Accept: text/html

new-item=Hello good sir

###
DELETE http://localhost:3000/myfile.txt
Accept: text/html

file=temp.txt

###
PUT http://localhost:3000/myfile.txt
Accept: text/html

content=Hello good sir

