GET http://localhost:3000/
Accept: text/html

###
POST http://localhost:3000/add
Content-Type: application/json

{
  "new-item": "Hello good sir"
}

###
DELETE http://localhost:3000/myfile.txt
Accept: text/html

###
PUT http://localhost:3000/myfile.txt
Accept: text/html
